Refactor ElementHandle evaluate calls
grafana/xk6-browser pull request #196
Opened 2022-01-19 13:19 UTC by inancgumus

This PR refactors `ElementHandle`'s evaluate calls that happen through the `ExecutionContext,` which are repetitive. This is not a critical change, but I worked on it while fixing #170, and wanted to create a separate PR.

2022-01-19 19:52 UTC, inancgumus reviewed
Self TODO.

2022-01-19 19:52 UTC, inancgumus commented on common/element_handle.go
> +	args = append(append([]interface{}(nil), script), args...)
Simplify.

2022-01-19 19:52 UTC, inancgumus commented on common/element_handle.go
> +	args = append(append([]interface{}(nil), h), args...)
Simplify.

2022-01-20 17:31 UTC, imiric requested changes
Very nice, this looks much cleaner now! :clap: It's always nice to see a net negative LOC refactor ;) Also, thanks for making this a separate PR, it would be too much to review with other changes.

Just left a few nitpicks about comments and such.

Re: converting arguments to `goja.Value`, that was what we did before anyway, right? So it shouldn't be a problem now.

2022-01-20 17:31 UTC, imiric commented on common/element_handle.go
> +// eval evaluates a given js function in the scope of this ElementHandle.
Similar to above:
```suggestion
// eval evaluates the given js code in the scope of this ElementHandle.
```

2022-01-20 17:31 UTC, imiric commented on common/element_handle.go
> +	result, err := h.execCtx.evaluate(ctx, opts, rt.ToValue(js), gargs...)
Same here about the comments being redundant, though the first one about ```passing `h` ...``` is somewhat useful. :)

Also, should we rename `ExecutionContext.evaluate` to `eval` as well, to make it consistent?

2022-01-21 11:47 UTC, inancgumus commented
> Very nice, this looks much cleaner now! 👏 It's always nice to see a net negative LOC refactor ;) Also, thanks for making this a separate PR, it would be too much to review with other changes.

Sure thing! Thanks for your kind words, @imiric, glad to hear :) Always helpful.

> Re: converting arguments to goja.Value, that was what we did before anyway, right? So it shouldn't be a problem now.

Fair enough!

2022-01-21 15:03 UTC, imiric approved these changes
LGTM

Remember to re-request a review when you're done with the changes.

2022-01-21 15:09 UTC, inancgumus commented
> Remember to re-request a review when you're done with the changes.

I usually do, but human nature, we're creatures that forget a lot 🤷 :)

2022-01-21 15:09 UTC, merged