Fix zombie browser processes
grafana/xk6-browser pull request #306
Opened 2022-05-10 10:36 UTC by inancgumus

This PR fixes #305 by closing the browser process whenever the context is canceled.

Before this fix, the browser processes keep open even after the test or k6 test runs. Especially for local tests, there were hundreds of zombie browser processes remain.

Fixes: #305

2022-05-10 14:18 UTC, ankur22 approved these changes

2022-05-10 18:16 UTC, inancgumus commented on common/browser.go
>  			case <-cancelCtx.Done():
Makes sense. See: https://github.com/grafana/xk6-browser/pull/306/commits/6069d61d6ad00a1215411fca49f9ac1e731a417e

PS: Welcome to your first review! 🎉

2022-05-11 09:13 UTC, imiric requested changes
LGTM, just remove that empty `common/browser_process` file.

I see how this could happen, but in practice I've never run into it, and can't reproduce it now on `main`.

I ran a few scripts allowing them to finish normally and also interrupting them with `^C`, and no zombie processes were left behind. I monitored it with `watch -n1 'pgrep -f chromium | wc -l'` and it always returned to the baseline number as before running the test. Maybe it's not a problem on Linux?

This shouldn't be a problem for our integration tests since [we cancel the context in `tb.Cleanup()`](https://github.com/grafana/xk6-browser/blob/eeab22ebfdc5c6d2863eab9a744ea1205d6d9309/tests/test_browser.go#L97). I couldn't reproduce it there either with `GOMAXPROCS=3 go test -p 3 -v -race -count=10 ./tests`.

Do you have a scenario that reproduces this?

2022-05-11 10:03 UTC, ankur22 commented
I've tried running the command `GOMAXPROCS=3 go test -p 3 -v -race -count=10 ./tests` against main and i was left with chrome process being left around after the tests eventually failed -- I had to restart my laptop since chrome became unusable. I'll try again on main to try and reproduce it one more time before trying it on the fix branch.

2022-05-11 10:19 UTC, inancgumus commented
> LGTM, just remove that empty `common/browser_process` file.

Ah, missed it 🤦 Thanks!

Like @ankur22, I used to restart my computer before the fix. I just ran the tests to reproduce it.

2022-05-11 10:40 UTC, imiric approved these changes
Sorry you suffered all this time Inanc :sweat:

I'm not sure why I've not run into this, but glad it's fixed now. :+1:

2022-05-11 10:46 UTC, merged

2022-05-11 10:57 UTC, ankur22 commented
> I've tried running the command `GOMAXPROCS=3 go test -p 3 -v -race -count=10 ./tests` against main and i was left with chrome process being left around after the tests eventually failed -- I had to restart my laptop since chrome became unusable. I'll try again on main to try and reproduce it one more time before trying it on the fix branch.
> 
> One of the zombie processes:
> 
> ```shell
> > lsof -p 88415
> COMMAND     PID         USER   FD   TYPE             DEVICE SIZE/OFF                NODE NAME
> chrome_cr 88415 ankuragarwal  cwd    DIR               1,13      512             3075289 /Users/ankuragarwal/go/src/github.com/grafana/xk6-browser/tests
> chrome_cr 88415 ankuragarwal  txt    REG               1,13  2151296             2745040 /Applications/Google Chrome.app/Contents/Frameworks/Google Chrome Framework.framework/Versions/101.0.4951.54/Helpers/chrome_crashpad_handler
> chrome_cr 88415 ankuragarwal  txt    REG               1,13    46688             2122161 /Library/Preferences/Logging/.plist-cache.SffiTnwv
> chrome_cr 88415 ankuragarwal  txt    REG               1,13  2160688 1152921500312781028 /usr/lib/dyld
> chrome_cr 88415 ankuragarwal    0r   CHR                3,2      0t0                 334 /dev/null
> chrome_cr 88415 ankuragarwal    1w   CHR                3,2      0t0                 334 /dev/null
> chrome_cr 88415 ankuragarwal    2   PIPE 0x1207757d8838958b    16384
> ```

Verified that the fix does indeed prevent any chrome zombie processes being left behind 🎉