Add locator.tap
grafana/xk6-browser pull request #401
Opened 2022-06-15 08:46 UTC by inancgumus

Closes #356.

2022-06-16 09:18 UTC, imiric requested changes
LGTM, just minor things.

Also, I think there's a bug here:
https://github.com/grafana/xk6-browser/blob/3ea1fdcfe4526151c7a4e126358001de9249f17b/common/element_handle.go#L593-L595

Shouldn't this be `tap(p.X, p.Y)`? Can you fix this in another PR?

2022-06-16 09:18 UTC, imiric commented on common/frame.go
> +// Tap the first element matches the selector.
```suggestion
// Tap the first element that matches the selector.
```

2022-06-16 09:18 UTC, imiric commented on tests/static/locators.html
> +            'touchstart', e => { result = true; }, false
```suggestion
            'touchstart', e => { window.result = true; }, false
```

2022-06-20 11:59 UTC, inancgumus commented on tests/static/locators.html
> +            'touchstart', e => { result = true; }, false
Thanks.

2022-06-20 12:00 UTC, inancgumus commented
> Also, I think there's a bug here:
> 
> https://github.com/grafana/xk6-browser/blob/3ea1fdcfe4526151c7a4e126358001de9249f17b/common/element_handle.go#L593-L595
> 
> Shouldn't this be `tap(p.X, p.Y)`? Can you fix this in another PR?

Nice catch! Thanks. I fixed it in this PR as the tap test needs the fix to work.

2022-06-20 12:48 UTC, ankur22 approved these changes

2022-06-20 12:49 UTC, merged